[tool.poetry]
name = "wink"
version = "0.1.0"
description = "wink"
authors = ["PocketBrain <tim.kirp@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
